spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/careconnect_auth
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8081

jwt:
  secret: aZ9f3kxk2VaDKtp81Gxbs9pG2eJl/s4ToOlzuyJExQFkjgx6nYp57VNk7SLFCUKaiW1f5WJLx1TaMy8Q4Z6AOA==
  access-token-expiration: 3600000  # 1 hour in ms
  refresh-token-expiration: 14400000  # 4 hours in ms

logging:
  level:
    org.springframework.security: DEBUG
