spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/careconnect_auth
    username: postgres
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8081

jwt:
  secret: my-secret-key-change-in-prod
  expiration: 3600000  # 1 hour in ms
